#!/usr/bin/env python
# -*- coding:utf-8 -*- 


##############################################################################
## license :
##============================================================================
##
## File :        RWrapper.py
## 
## Project :     R wrapper
##
## This file is part of Tango device class.
## 
## Tango is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Tango is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Tango.  If not, see <http://www.gnu.org/licenses/>.
## 
##
## $Author :      havasd$
##
## $Revision :    $
##
## $Date :        $
##
## $HeadUrl :     $
##============================================================================
##            This file is generated by POGO
##    (Program Obviously used to Generate tango Object)
##
##        (c) - Software Engineering Group - ESRF
##############################################################################

"""Tango device server which wraps the R language."""

__all__ = ["RWrapper", "RWrapperClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(RWrapper.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	RWrapper.additionnal_import

## Device States Description
## RUNNING : Runs the given command.
## STANDBY : It`s possible to extract the results of a previous command or run a new command.

class RWrapper (PyTango.Device_4Impl):

    #--------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(RWrapper.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	RWrapper.global_variables

    def __init__(self,cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        RWrapper.init_device(self)
        #----- PROTECTED REGION ID(RWrapper.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(RWrapper.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_result_read = ''
        #----- PROTECTED REGION ID(RWrapper.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(RWrapper.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.always_executed_hook

    #-----------------------------------------------------------------------------
    #    RWrapper read/write attribute methods
    #-----------------------------------------------------------------------------
    
    def read_result(self, attr):
        self.debug_stream("In read_result()")
        #----- PROTECTED REGION ID(RWrapper.result_read) ENABLED START -----#
        attr.set_value(self.attr_result_read)
        
        #----- PROTECTED REGION END -----#	//	RWrapper.result_read
        
    def write_result(self, attr):
        self.debug_stream("In write_result()")
        data=attr.get_write_value()
        #----- PROTECTED REGION ID(RWrapper.result_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.result_write
        
    
    
        #----- PROTECTED REGION ID(RWrapper.initialize_dynamic_attributes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.initialize_dynamic_attributes
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(RWrapper.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.read_attr_hardware


    #-----------------------------------------------------------------------------
    #    RWrapper command methods
    #-----------------------------------------------------------------------------
    
    def runCommand(self, argin):
        """ Runs the given R command in R
        
        :param argin: 
        :type: PyTango.DevString
        :return: 
        :rtype: PyTango.DevVoid """
        self.debug_stream("In runCommand()")
        #----- PROTECTED REGION ID(RWrapper.runCommand) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.runCommand
        
    def is_runCommand_allowed(self):
        self.debug_stream("In is_runCommand_allowed()")
        state_ok = not(self.get_state() in [PyTango.DevState.RUNNING])
        #----- PROTECTED REGION ID(RWrapper.is_runCommand_allowed) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.is_runCommand_allowed
        return state_ok
        
    def getResult(self):
        """ Returns the output of the previoiusly executed R command
        
        :param : 
        :type: PyTango.DevVoid
        :return: 
        :rtype: PyTango.DevString """
        self.debug_stream("In getResult()")
        argout = ''
        #----- PROTECTED REGION ID(RWrapper.getResult) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.getResult
        return argout
        
    def is_getResult_allowed(self):
        self.debug_stream("In is_getResult_allowed()")
        state_ok = not(self.get_state() in [PyTango.DevState.RUNNING])
        #----- PROTECTED REGION ID(RWrapper.is_getResult_allowed) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.is_getResult_allowed
        return state_ok
        

class RWrapperClass(PyTango.DeviceClass):
    #--------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(RWrapper.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	RWrapper.global_class_variables

    def dyn_attr(self, dev_list):
        """Invoked to create dynamic attributes for the given devices.
        Default implementation calls
        :meth:`RWrapper.initialize_dynamic_attributes` for each device
    
        :param dev_list: list of devices
        :type dev_list: :class:`PyTango.DeviceImpl`"""
    
        for dev in dev_list:
            try:
                dev.initialize_dynamic_attributes()
            except:
                import traceback
                dev.warn_stream("Failed to initialize dynamic attributes")
                dev.debug_stream("Details: " + traceback.format_exc())
        #----- PROTECTED REGION ID(RWrapper.dyn_attr) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	RWrapper.dyn_attr

    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        'runCommand':
            [[PyTango.DevString, "none"],
            [PyTango.DevVoid, "none"]],
        'getResult':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevString, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'result':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(RWrapperClass,RWrapper,'RWrapper')

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed,e:
        print '-------> Received a DevFailed exception:',e
    except Exception,e:
        print '-------> An unforeseen exception occured....',e

if __name__ == '__main__':
    main()
